.env.template
Dockerfile
README.md
docker-compose.yml
pyproject.toml

Docker Image is based off a py3.12 base image. It installs a postgres driver, an aws rds cert (via curl), and poetry. Then it copies the pyproject toml file and the py source code and builds it.
Docker Compose file uses this docker image and a postgres15.4 image to stand up the application for local testing.
.env.template file contains all the evn variables that need to be defined to run locally.
update readme with more dev steps to get the docker images up and running.

Add Docker Image and Docker Compose

---

Dockerfile

RDS Connection requires `rds-ca-ecc384-g1` contained in AWS Global cert bundle

FIX: Update cert bundle for RDS connection

---

src/dmap_import/util_api.py

Retry logic on GET Requests was not working as  expected, based on logging from initial application run. 
New retry logic should be more robust and provide expected behavior.

FIX: Retry logic on GET Requests

---

.github/workflows/deploy_to_prod.yaml

This deployment will be triggered when new version tags are pushed up to origin or via a manual dispatch. It follows the same actions as the staging deployment, but with the prod environment variable.

FEAT Add a new deployment workflow for prod

---

src/dmap_import/pipeline.py
src/dmap_import/util_aws.py
src/dmap_import/util_rds.py

Although unlikely because of the configuration in our infrastructure, the dmap import task could be ran more than once in parallel. If they were both writing to the RDS at the same time, chaotic behavior could result.
To prevent this, check for parallel tasks before starting the main process using a boto3 ecs client.

FEAT: Check for Parallel ECS Tasks

---

README.md
src/alembic/versions/002_0d3bf1348c58_new_reference_org_name_columns.py
src/dmap_import/schemas/sale_transaction.py
src/dmap_import/schemas/use_transaction_location.py
src/dmap_import/schemas/use_transaction_longitudinal.py

Tackling issues:
* [P0 `use_transaction` does not distinguish test data from real data](https://app.asana.com/0/1198515006893726/1206006813953829)

feat: add reference fields

---

README.md
docker-compose.yml
src/alembic/versions/003_fb033ef6de1b_add_reference_notes_column.py
src/dmap_import/schemas/sale_transaction.py
src/dmap_import/schemas/use_transaction_location.py
src/dmap_import/schemas/use_transaction_longitudinal.py

Cubic has renamed the `reference` column to `reference_notes`. Since this work was deployed, I need to have a new migration to support this new column.

feat: add reference_notes column

---

src/cubic_loader/qlik/ods_qlik.py

We don't care about changes in ordinal value, this can be ignore. Including it is causing failures to load files for ods-qlik process.

FIX: Ignore Oridnal column in schema files

---

src/cubic_loader/qlik/ods_qlik.py
src/cubic_loader/qlik/rds_utils.py

The original implementation of the ODS-QLIK RDS loader assumed that new snapshots would not be created. An assert check made sure that this condition stopped any loading operation if a new snapshot was detected.
This change loads new QLIK snapshots by totally wiping out the existing history and fact tables and loading the newest snapshot that is found. 
With this implementation all transaction history will be lost any time cubic restarts the QLIK replication process. 
This change requires that the application ECS be given DELETE permission for the application status files on S3. 
Devops PR: https://github.com/mbta/devops/pull/2170

FEAT: Reset ODS tables for new QLIK Snapshot

---

src/cubic_loader/qlik/ods_qlik.py

ODS-QLIK table loading for `EDW.PATRON_TRIP` is currently not functional. 
This is because the latest initial snapshot folder (based on timestamp) is currently located in the data-platform error bucket. While the snapshot folder that the cubic qlik process is populating is in the archive bucket. 
Having the ods-qlik loader only look for snapshot files in the archive bucket will fix this issue for the `EDW.PATRON_TRIP` table. However, if an initial snapshot folder is moved to the error bucket, and remains in-use by the cubic ods-qlik process, then this functionality will again be broken.

FIX: Only load initial snapshot folders from the archive bucket

---

src/cubic_loader/qlik/ods_qlik.py
src/cubic_loader/qlik/rds_utils.py
src/cubic_loader/qlik/utils.py
src/cubic_loader/utils/postgres.py

This change alters the way ods-qlik data is loaded into the dmap-import database.
Previously the ods-qlik data loading steps where:
1. load individual cdc csv.gz files into `_history` table
2. execute very complicated query against history table to generate `_fact` table updates.
This approach has proven to not be scalable, as the size of the `_history` tables and complicated nature of the `_fact` table query, has resulted in unacceptable long load times.
The new process does the following:
1. download batches of cdc csv.gz files on to local machine
2. merge file batches into a single csv file
3. load csv file to `_history` table
4. convert csv file to dataframe object
5. perform INSERT - UPDATE - DELETE operations on `_fact` table individually with dataframe object
The new process …

FEAT: Decrease run-time duration of ODS-QLIK Process

---

.github/workflows/run-task.yaml

New Github action for manually triggering run of `dmap-import` task. 
Relies on a couple other PRs to be implemented: 
https://github.com/mbta/actions/pull/62
https://github.com/mbta/devops/pull/2261

FEAT: run dmap-import task via GHA

---

src/cubic_loader/dmap/api_copy_job.py

The change logs an Error/Exception if dmap-import API download contains no records. 
Cubic should not be publishing API downloads without records. This change will propagate notifications of empty dmap datasets to splunk alerts. 
Asana Task: https://app.asana.com/0/1203883924584572/1208782928208814

[dmap-import] FEAT: Log error when DMAP API file contains no records.

---

src/cubic_loader/qlik/ods_tables.py

Been meaning to add this table. But Policy made an ask today for this data that links Contactless to RF credentials (charliecard #)

chore: table for policy analysis

---

src/alembic/versions/007_96837b10c106_reset_qlik_null_key_tables.py
src/cubic_loader/qlik/rds_utils.py

PR #34 allowed ODS Primary Key columns to contain NULL values. However, this change broke our updating process because NULL != NULL when doing JOIN operations. 
This change joins Primary Key columns using `IS NOT DISTINCT FROM` instead of `=` to allow for the JOINING of NULL to NULL values in Key columns. 
This change also contains a migration that deletes the ELT Status files for all tables loaded since PR #34 so that those tables will be re-loaded with the new loading process.

FIX: Handle NULL values in Key columns for Update operation

---

src/alembic/versions/007_96837b10c106_reset_qlik_null_key_tables.py
src/cubic_loader/qlik/ods_qlik.py
src/cubic_loader/qlik/rds_utils.py
src/cubic_loader/qlik/utils.py

Two changes in this PR:
1. Explicitly drop these tables when deleting the status files to force full table reset. 
2. Dynamically select join operation (`=` or `IS NOT DISTINCT FROM`) in update and delete operations based on presence of NULL values in key columns. 
Change 2 was made because using `IS NOT DISTINCT FROM` has huge implications on query performance so it should only be used where absolutely necessary.

FIX: Drop Tables for migration / Dynamic JOIN operation

---

src/alembic/versions/008_2d6f7140c642_wc_700_comp_a_b.py

This change creates views for the WC700 Comp A&B Reports. SQL for these reports was provided by Cubic.
Reports are grouped by primarily (settlement_day_key, operating_day_key & payment_type_key).

FEAT: Create VIEWS for WC700 Comp A&B Reports

---

src/alembic/versions/008_2d6f7140c642_wc_700_comp_a_b.py

Staging is failing on this migration because ODS tables do not exist.
This was already successfully deployed to PROD.

FIX: Staging failing on 2d6f7140c642 migration

---

src/cubic_loader/dmap/dmap_api.py

The DMAP-IMPORT API loading process has recently been throwing alerts because certain tables are not getting loaded with new results. 
This issue has been caused by the API limiting the number of results, per request, to 100. 
Previously, it was documented that the `offset` parameter had no impact on returned results. However, it appears that the `offset` parameter is now working and can be used to gather more than 100 results from the API. 
This change allows for the pulling of up to 1000 results from the API to ensure that subsequent filtering on the `last_updated` result-field does not make it appear as if no results are available for loading.

FIX: Use DMAP API "offset" param for more than 100 results

---

src/alembic/versions/011_bf94c2890bc9_pk_id_to_bigint.py
src/cubic_loader/dmap/schemas/device_event.py
src/cubic_loader/dmap/schemas/sale_transaction.py
src/cubic_loader/dmap/schemas/use_transaction_location.py
src/cubic_loader/dmap/schemas/use_transaction_longitudinal.py

Prod environment throwing errors because `pk_id` column hit the maximum Integer value.
```
nextval: reached maximum value of sequence "device_event_pk_id_seq" (2147483647)
```
This changes updates the `pk_id` column for large dmap tables to use BigInteger, with much larger maximum value. 
This issues does not impact ODS tables, as all of the ODS field types are dictated by QLIK dfm files.

FIX[dmap-import]: Change pk_id to BigInteger for large tables.

---

src/alembic/versions/007_96837b10c106_reset_qlik_null_key_tables.py
src/alembic/versions/012_be5284c3563e.py
src/cubic_loader/qlik/ods_qlik.py
src/cubic_loader/qlik/sql_strings/views.py

This change includes the following:
- No longer dropping ODS fact tables during spanshot reset, truncate instead (this was causing views to drop)
- Recreate WC700 Views dropped during snapshot reset.
- Create ad_hoc_processed_taps View with associated index.

FIX: ODS Views and dmap-import sequences

---

src/alembic/versions/013_1dc0843c9d69.py
src/cubic_loader/pipeline.py
src/cubic_loader/qlik/sql_strings/mat_views.py
src/cubic_loader/utils/postgres.py

This change adds the query for WC700 Comp-B Addendum as a materialized view. 
The materialized view is added to the DB as a migration and then refreshed after new qlik-ods data is loaded using NEW!! `DatabaseManager.refresh_mat_views()` method.

FEAT: WC700 Comp-B Addendum as Materialized VIEW

---

.envrc
src/cubic_loader/qlik/ods_qlik.py
src/cubic_loader/utils/remote_locations.py

We will be turning `odin` on for PROD shortly, so the `dmap-import` Qlik job will need to read from the ODIN Archive partition for each ODS table.

FEAT: Use odin archive partition as ods_qlik Job Source

---

src/cubic_loader/qlik/ods_qlik.py

Odin PROD Cubic ODS-Qlik processing has been temporarily suspended while a few qlik related issues are resolved. 
This change will read files from old Qlik Archive location temporarily.

temp: Revert back to reading from QLIK archive location 

---

src/cubic_loader/pipeline.py
src/cubic_loader/qlik/ods_qlik.py

Load snapshot paths from ODIN processed and catch CubicODSQlik Class creation errors.

FIX: Catch CubicODSQlik Creation Error

---

src/cubic_loader/qlik/ods_qlik.py
src/cubic_loader/qlik/utils.py

~~dmap-import ECS is dying without any logging output, presumable from OOM errors when loading EDW.CCH_AFC_TRANSACTION change files.~~
~~It's unclear why this would begin happening all of a sudden, as the current check limits the folder size to 60MB. This change reduces the folder size limit to 30MB to see if the CCH_AFC_TRANSACTION table change files can be loaded~~.
Scratch that, after literal minutes of reflection. I think this issue might be caused by a csv.gz zip bomb blowing up the ECS memory. 
When loading CDC files the Qlik process keeps track of the total `csv.gz` file sizes in a folder and processes the folder when they reach a limit (~60mb). However if this is extremely sparse data, the csv.gz compression could be causing an in-memory zip bomb when the highly compressed, and …

FIX: Reduce size of cdc load folder size

---

src/alembic/versions/015_4b8117e23c8e_wa160_view.py
src/cubic_loader/qlik/sql_strings/views.py

This change adds a view to the dmap-import db, at the request of the MBTA finance team.
The new view is the WA160 report. Several original columns of this report have been removed as they produced all NULL results.
Asana task: https://app.asana.com/1/15492006741476/project/1208949713596457/task/1210511428402701

feat: add wa160 view to dmap-import

---

Dockerfile

`dmap-import` makes heavy use of /tmp folder file writing, which seems like is being reported as excessive memory usage causing the ECS to be killed.
This change deploys the "tmp folder fix" that other ECS instances have deployed to resolved this issue.
Deploy will need to be coordinated with additional infra PRs. terraform modules PR already created: https://github.com/mbta/terraform_modules/pull/259

fix: /tmp folder mem leak fix

---

src/cubic_loader/pipeline.py
src/cubic_loader/qlik/ods_qlik.py

Qlik process appears to be leaking memory between table runs.
This change runs each CubicODSQlik table instance in it's own process to hopefully clean up this memory leak. the DatabaseManager object can not be pickled into the process before running, so new DatabseManager must be created when each table instance runs.

FIX: run CubicODSQlik in each own process

---

src/alembic/versions/018_76a64efdbdd9_alter_fare_prod_id_varchar.py
src/cubic_loader/dmap/schemas/sale_transaction.py
src/cubic_loader/dmap/schemas/use_transaction_location.py
src/cubic_loader/dmap/schemas/use_transaction_longitudinal.py

Cubic has communicated that the `fare_prod_id` field in all dmap tables will be changing to a varchar/string type.
This change contains the migration required to update this field in the dmap-import DB.
Asana task: https://app.asana.com/1/15492006741476/project/1208949713596462/task/1210986298091645

fix: dmap fare_prod_id to string

---

src/alembic/versions/019_92ab6c167c5b_feat_add_validator_interface_to_use_.py

From [Asana](https://app.asana.com/1/15492006741476/project/546643571451005/task/1211027616797708?focus=true)
7/29: adding VALIDATOR_INTERFACE (in ODS) to dmap. additional column from use_transaction - please submit service now request.
*Dave add a ticket for this 8/12 - REQ0284902 / RITM0338851
[CHG0110025 | Change Request | ServiceNow](https://ctscubic.service-now.com/nav_to.do?uri=%2Fchange_request.do%3Fsys_id%3D33df675a2befe69472d8f4f9dd91bf6e%26sysparm_view%3D%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull)
Add validator_interface to use_transaction API extracts
Scheduled for 27th Aug 10 AM - 12 PM IST / 4:30 AM to 6:30 AM UTC

feat: add validator_interface column to use_transaction_*
